### PR TITLE
Fix PED bugs

### LINKED ISSUE #168: [PE-D][Tester D] Parsing invalid dates
Program accepts invalid dates such as 29-02-2023 and parses it as 28-02-2023 instead of just rejecting the command.

This error can be seen when parsing dates on months with less than 31 days.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: shamooose/ped#1

### LINKED ISSUE #176: [PE-D][Tester C] Pressing enter will not execute search
When typing `search n/David`, the autocomplete comes out. However, pressing the enter key does not execute anything, unless I use my cursor to click on that name, which is not a command line interface as described in the user guide. One way to get around it is to hold down the enter key, which works but is odd.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: cadencjk/ped#2

### LINKED ISSUE #177: [PE-D][Tester D] Spelling error
Spelling error in message displayed for todo show [date range] error.
Should be 'later' instead of 'latter'

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: shamooose/ped#2

### LINKED ISSUE #189: [PE-D][Tester C] Date error message does not return the correct message
todo edit 2 date/32-10-2022

I parsed in the correct date format, just that the date does not exist, but the application returned with a date format error message.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: cadencjk/ped#5

### LINKED ISSUE #193: [PE-D][Tester E] Improper handling of date that does not exist
<i><video controls><source src="https://raw.githubusercontent.com/yixiann/ped/main/files/d8190211-b49e-4b07-85fb-2f8bcd8f0899.mov" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/yixiann/ped/main/files/d8190211-b49e-4b07-85fb-2f8bcd8f0899.mov</i>

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: yixiann/ped#12

### LINKED ISSUE #202: [PE-D][Tester E] Missing linebreak and wrong date format
The date should not be using "/"

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: yixiann/ped#14

### LINKED ISSUE #204: [PE-D][Tester C] Wrong suffix used
Listing 1 todo returns a `1 todos listed` even though there is only one todo. Singular `todo` should be used instead of plural `todos`.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: cadencjk/ped#10

### LINKED ISSUE #211: [PE-D][Tester A] Not accurate message error when typing todo
The error should be please enter a valid date as user might not understand why this error statement came out after typing it in the correct format.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: LolfoollorS/ped#11

### LINKED ISSUE #213: [PE-D][Tester A] Either incorrect error message was shown or for some reason the program think there is dupe task when it doesn't exist
<i><video controls><source src="https://raw.githubusercontent.com/LolfoollorS/ped/main/files/0d7f7400-6fd5-446f-b337-79d215d79d3f.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/LolfoollorS/ped/main/files/0d7f7400-6fd5-446f-b337-79d215d79d3f.mp4</i>

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: LolfoollorS/ped#13

### LINKED ISSUE #214: [PE-D][Tester A] Able to add dates that is incorrect and auto edit it to the latest date.
input: `todo add d/A date/31-02-2022 pr/high`
expected: invalid date error message
output: `New Todo added: A; Date: 28 Feb 2022; Priority: high`

Initally, I thought that this a neet feature but then I thought about it, this program would have issues every leap year for feb and not to mention the user might have just accidently type wrongly the month which if you do not have this feature, this wouldn't happen. But since this occured, the user need to delete and re-add again. Also if this is actually a feature might want to put it in User guide. (Could be Documentation bug) 

<i><video controls><source src="https://raw.githubusercontent.com/LolfoollorS/ped/main/files/95aeea61-07c8-4a35-8569-712604d9103a.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/LolfoollorS/ped/main/files/95aeea61-07c8-4a35-8569-712604d9103a.mp4</i>

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: LolfoollorS/ped#14

### PR DESCRIPTION
**Pull request by Ugholaf**
- Fix https://github.com/AY2223S1-CS2103T-W15-1/tp/issues/214
- Fix https://github.com/AY2223S1-CS2103T-W15-1/tp/issues/213
- Fix https://github.com/AY2223S1-CS2103T-W15-1/tp/issues/211
- Fix https://github.com/AY2223S1-CS2103T-W15-1/tp/issues/204
- Fix https://github.com/AY2223S1-CS2103T-W15-1/tp/issues/202 
- Fix https://github.com/AY2223S1-CS2103T-W15-1/tp/issues/193
- Fix https://github.com/AY2223S1-CS2103T-W15-1/tp/issues/189
- Fix https://github.com/AY2223S1-CS2103T-W15-1/tp/issues/177
- Fix https://github.com/AY2223S1-CS2103T-W15-1/tp/issues/168
- Fix https://github.com/AY2223S1-CS2103T-W15-1/tp/issues/176

### CODE REVIEW

File: src/main/java/soconnect/ui/CommandBox.java [hunk 1]
```diff
@@ -90,21 +95,13 @@ private void setAutocompleteListener() {
...
-                switch (event.getCode()) {
-                case UP:
-                case DOWN:
-                case LEFT:
-                case RIGHT:
-                case SPACE:
-                    break;
-                default:
-                    autocompleteAction();
-                }
```
Comment (florentianayuwono) [inline src/main/java/soconnect/ui/CommandBox.java:105]: What's the consequence of erasing the UP DOWN, etc part?

**Review by florentianayuwono — COMMENTED** [review]
Looks good to me, just a question!

File: src/main/java/soconnect/ui/CommandBox.java (hunk 1 above)
Comment (Ugholaf) [reply src/main/java/soconnect/ui/CommandBox.java:105]: Nothing will happen. Initially, I made the Key listener not generate autocomplete when the UP DOWN keys are pressed because I wanted to update the text in the command box when the user chooses the autocomplete entries using the arrow key. But since I can't figure out a way to make this behaviour happen, so I decided to remove it.

**Review by florentianayuwono — APPROVED** [review]
I see, LGTM then!
