### PR TITLE
Improve relevant search and fix bugs

### LINKED ISSUE #115: Relevant search to only return result based on prefix specified
`search n/al` will only return contacts with name that contains `al`, will not match to other prefixes like `address`, etc.

### LINKED ISSUE #116: Invalid search command is not handled properly
`search n/` doesn't return error message.

### PR DESCRIPTION
**Pull request by florentianayuwono**
- Relevant search now only search according to the prefix specified.
- Exception handled for invalid command input.

### CODE REVIEW

File: src/main/java/soconnect/model/person/search/ContactMightBeRelevantPredicate.java [hunk 1]
```diff
@@ -1,43 +1,70 @@
...
+                                .containsSomeKeywordsIgnoreCase(person.getPhone().value, keyword));
+                break;
+            case TAG:
+                isTagContained = keywords.stream()
+                        .anyMatch(keyword -> person.getTags().stream()
+                                .anyMatch(tag -> StringUtil
+                                        .containsSomeKeywordsIgnoreCase(tag.tagName, keyword)));
+                break;
+            default:
+                break;
```
Comment (ChongCheeKaiClarence) [inline src/main/java/soconnect/model/person/search/ContactMightBeRelevantPredicate.java:54]: Are you sure it is fine to leave it as just `break`? I think maybe u could throw an exception. Or use assertions instead.

File: src/main/java/soconnect/logic/commands/SearchCommand.java [hunk 2]
```diff
@@ -44,7 +45,11 @@ public SearchCommand(Predicate<Person> predicate, Predicate<Person> alternativeP
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
-        model.updateFilteredPersonList(predicate);
+        try {
+            model.updateFilteredPersonList(predicate);
+        } catch (Exception e) {
```
Comment (ChongCheeKaiClarence) [inline src/main/java/soconnect/logic/commands/SearchCommand.java]: Are you sure it is a good idea to catch `exception`? Is there anything more specific?

**Review by ChongCheeKaiClarence — CHANGES_REQUESTED** [review]
Overall, Great Work! But, I just have a few questions. Could you clarify them?

File: src/main/java/soconnect/model/person/search/ContactMightBeRelevantPredicate.java [hunk 3]
```diff
@@ -1,43 +1,70 @@
...
+            case PHONE:
+                isPhoneContained = keywords.stream()
+                        .anyMatch(keyword -> StringUtil
+                                .containsSomeKeywordsIgnoreCase(person.getPhone().value, keyword));
+                break;
+            case TAG:
+                isTagContained = keywords.stream()
+                        .anyMatch(keyword -> person.getTags().stream()
+                                .anyMatch(tag -> StringUtil
+                                        .containsSomeKeywordsIgnoreCase(tag.tagName, keyword)));
```
Comment (Eugene-Ong-W-X) [inline src/main/java/soconnect/model/person/search/ContactMightBeRelevantPredicate.java]: This method exceeds 30LOC, you can shorten it by abstract out each of the 5 cases above.
E.g. isNameContained = containsNameKeyword(keywords);

**Review by Eugene-Ong-W-X — COMMENTED** [review]
Nice work, only left 1 comment about abstraction for a method that is too long.

File: src/main/java/soconnect/model/person/search/ContactMightBeRelevantPredicate.java (hunk 1 above)
Comment (florentianayuwono) [reply src/main/java/soconnect/model/person/search/ContactMightBeRelevantPredicate.java:54]: Actually, if I am not wrong, I cannot really throw exception because it is already outside of the parser class. And it is not suitable because this class is inheriting the Predicate class and the method `test` is overriding the parent `test` method. I tried but couldn't. Therefore I designed it in such a way that it will never actually reach the default case. This is because the parser only parse the argument like this:
`        ArgumentMultimap argMultimap =
                ArgumentTokenizer.tokenize(args, PREFIX_NAME, PREFIX_PHONE, PREFIX_EMAIL, PREFIX_ADDRESS, PREFIX_TAG);`

This will cause the tokenizer to only tokenize the valid prefixes. 

I tried using assertions also, but it cause the valid search to also cause error :")

Please suggest if you have idea to double defense it safely :)

Comment (florentianayuwono) [reply src/main/java/soconnect/model/person/search/ContactMightBeRelevantPredicate.java:54]: Hey, update! Although I am still unable to throw exception, thanks to this I discover some bugs and manage to turn it into improvement in relevant search instead :DD

So since the `argMultimap` will just tokenize the valid prefixes, when we feed in args like `search n/alex h/yeoh`, even though the `h/yeoh` is invalid, it will map it as `[prefix_name, alex h/yeoh]`, aka it will treat the entirety as name. This instead is not handled well by the pervious search algorithm, as it will just return empty list of person.

However, now it will return `alex yeoh` instead! And even if the user types in `search n/a+l+e+x`, or some other weird combinations, it will still be able to return relevant result. Contrastingly, if the user types in `search f/hello` or `search n/++`, then it will return the `invalid_format` error.

So thank you! :D

File: src/main/java/soconnect/logic/commands/SearchCommand.java (hunk 2 above)
Comment (florentianayuwono) [reply src/main/java/soconnect/logic/commands/SearchCommand.java]: No, it's not a good idea haha. I am just honestly paranoid that some exceptions I don't know are not handled well. But yes, this is not good too. After some screening, I managed to reduce it to null and invalid argument exception, though let's hope that indeed no exception is not handled and this is just a paranoia.

File: src/main/java/soconnect/model/person/search/ContactMightBeRelevantPredicate.java (hunk 3 above)
Comment (florentianayuwono) [reply src/main/java/soconnect/model/person/search/ContactMightBeRelevantPredicate.java]: Nice catch, thank you!

File: src/main/java/soconnect/model/person/search/ContactMightBeRelevantPredicate.java (hunk 1 above)
Comment (ChongCheeKaiClarence) [reply src/main/java/soconnect/model/person/search/ContactMightBeRelevantPredicate.java:54]: Wow. That's great! Keep up the good work!
