### PR TITLE
Fix bugs and add test cases for Search Feature

### LINKED ISSUE #64: Bug: Search feature does not handle invalid arguments
### Bug found during testing
The input `search a/Blk and n/alice` and `search a/Blk AnotherWord` does not give an appropriate warning to the user.
The reason seems to be that the case of having multiple words for an attribute is not handled.

### Attached Screenshots of Bug
image
image

### PR DESCRIPTION
**Pull request by florentianayuwono**
Fix #64

### CODE REVIEW

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 1]
```diff
@@ -38,6 +39,29 @@ public static boolean containsWordIgnoreCase(String sentence, String word) {
...
+     *       containsWordIgnoreCase("ABc def", "abc") == true
+     *       containsWordIgnoreCase("ABc def", "abc DEF") == true
+     *       containsWordIgnoreCase("ABc def", "AB") == false //not a full word match
+     *       </pre>
+     * @param sentence cannot be null
+     * @param keywords cannot be null, cannot be empty, can be multiple words
+     */
+    public static boolean containsKeywordsIgnoreCase(String sentence, String keywords) {
+        requireNonNull(sentence);
+        requireNonNull(keywords);
```
Comment (Eugene-Ong-W-X) [inline src/main/java/seedu/address/commons/util/StringUtil.java]: `requireAllNonNull(sentence, keywords)`

**Review by Eugene-Ong-W-X — COMMENTED** [review]
1 minor change suggested. Great job 👍

**Comment by Eugene-Ong-W-X** [comment]
LGTM
